### PR TITLE
Refactoring code

### PR DESCRIPTION
**Pull request by dzhalaevd**
1. Simplified most of the if conditions
2. removed nested conditions
3. Fix typos.
4. Renamed most variables to meet the requirements of PEP 8
5. Added indents, tabs wherever needed according to the recommendations of PEP 8
6. Fixed typos and added TODO for the future
7. I divided 1 file into several so that there was no legacy code
8. I moved the main code to ```main.py```

If you have any questions, you can ask them to me.

### CODE REVIEW

**Comment by snekbeater** [comment]
Thank you for the clean up! That looks impressive! One design idea of scramb.py was that it is one .py file, so would it be possible to integrate everything back to one file? Of course that is more cumbersome for authors, but easier to handle for users (and easier to distribute scramb.py because it is just one file). What do you think?

**Comment by dzhalaevd** [comment]
> Thank you for the clean up! That looks impressive! One design idea of scramb.py was that it is one .py file, so would it be possible to integrate everything back to one file? Of course that is more cumbersome for authors, but easier to handle for users (and easier to distribute scramb.py because it is just one file). What do you think?

On the one hand, yes, but over time it will be harder and harder to supplement the code and add new functions. Plus I would like to change a couple more functions in the coming week. And so yes, in principle it is possible to return everything to one file, but still, it's hard to work with so many functions in one file

**Comment by snekbeater** [comment]
Ok, I will look into it, especially run my testsetup with the changed code tomorrow.
I will also look into how to upload the testsetup and its images, this should help.
Do you plan to commit / contribute the new functions to this main branch here?
Can you tell me, what you plan to add or change?
I have stubs/prototypes here for higher density byte snake encoding (more bytes per block) for possible payload / file integration; for quality-of-output-image optimization (this is why some of the comparison / residue functions are present in the code but not used :-O ) ; and a started javascript version for Grease Monkey or a static website.
And another idea on the list is of course some GUI for easier handling by non CLI-Users

**Comment by dzhalaevd** [comment]
> Ok, I will look into it, especially run my testsetup with the changed code tomorrow.
> I will also look into how to upload the testsetup and its images, this should help.
> Do you plan to commit / contribute the new functions to this main branch here?
> Can you tell me, what you plan to add or change?
> I have stubs/prototypes here for higher density byte snake encoding (more bytes per block) for possible payload / file integration; for quality-of-output-image optimization (this is why some of the comparison / residue functions are present in the code but not used :-O ) ; and a started javascript version for Grease Monkey or a static website.
> And another idea on the list is of course some GUI for easier handling by non CLI-Users

Well, it turns out, as you asked, I will transfer everything to one file. 

And maybe I'll simplify the functions (if you follow the principles of pure code, then the function should not exceed 20 lines), but I'm not sure I'll have time, so it's inaccurate. Maybe I'll do a new PR for the feature

**Comment by dzhalaevd** [comment]
> Ok, I will look into it, especially run my testsetup with the changed code tomorrow. I will also look into how to upload the testsetup and its images, this should help. Do you plan to commit / contribute the new functions to this main branch here? Can you tell me, what you plan to add or change? I have stubs/prototypes here for higher density byte snake encoding (more bytes per block) for possible payload / file integration; for quality-of-output-image optimization (this is why some of the comparison / residue functions are present in the code but not used :-O ) ; and a started javascript version for Grease Monkey or a static website. And another idea on the list is of course some GUI for easier handling by non CLI-Users

That's it, I moved everything to one file scramb.py. You can test and approve PR :)

**Comment by snekbeater** [comment]
Started to looking into, sorry, I had no time before -- ok, I have to go through the code more in deep, it takes a lot of time since also format is changed (spaces vs tab etc) -- so diff with "eyes"

First test run almost resulted in all Fail, sorry :-O

(ignore that a lot of lines are doubled)
cat test.log:
Testrun
[FAIL] Test big mask and png input
[ OK ] Test big mask and png input
[ OK ] Different Datafield
[ OK ] Unscramble unscrambled image
[ OK ] Corrupted Image throu Logo
[FAIL] Drag & Drop Filename V01 Encoder
[FAIL] Drag & Drop Filename V01 Encoder
[FAIL] Even medium
[FAIL] Even medium
[FAIL] Uneven medium
[FAIL] Uneven medium
[FAIL] Uneven heavy
[FAIL] Uneven heavy
[FAIL] matrix full image (no .png)
[FAIL] matrix full image (no .png)
[FAIL] descramble matrix full image (no .png)
[FAIL] descramble matrix full image (no .png)
[FAIL] matrix full image (no .png), blowup
[FAIL] matrix full image (no .png), blowup
[FAIL] descramble matrix full image (no .png), blowup
[FAIL] descramble matrix full image (no .png), blowup
[FAIL] uneven by 8 image
[FAIL] uneven by 8 image
[FAIL] descramble uneven by 8 image
[FAIL] descramble uneven by 8 image
[FAIL] uneven by 8 checkerboard
[FAIL] uneven by 8 checkerboard
[FAIL] descramble uneven by 8 checkerboard
[FAIL] descramble uneven by 8 checkerboard
[FAIL] checkerboard heavy, y set
[FAIL] checkerboard heavy, y set
[FAIL] checkerboard heavy descramble, y set
[FAIL] checkerboard heavy descramble, y set
[FAIL] text test, medium xyz set
[FAIL] text test, medium xyz set
[ -- ] descramble text test with prompt, medium xyz set
[FAIL] descramble text test, silent mode, medium xyz set
[FAIL] descramble text test, silent mode, medium xyz set
[FAIL] text test, medium xyz set
[FAIL] text test, medium xyz set
[FAIL] descramble text test, medium xyz set
[FAIL] descramble text test, medium xyz set
[FAIL] sw image (Luma Mode), no logo
[FAIL] sw image (Luma Mode), no logo
[FAIL] descramble text test, medium xyz set
[FAIL] descramble text test, medium xyz set
[ -- ] huge image, matrix
[ -- ] descramble huge image, matrix
[FAIL] create a patch image
[FAIL] create a patch image
[FAIL] patch an image (descramble)
[FAIL] patch an image (descramble)
[FAIL] create a patch image (portrait mode) x2
[FAIL] create a patch image (portrait mode) x2
[FAIL] patch an image (descramble) (portrait mode)
[FAIL] patch an image (descramble) (portrait mode)
[FAIL] create a patch image,blowup, password
[FAIL] create a patch image,blowup, password
[FAIL] patch an image (descramble), blowup, password
[FAIL] patch an image (descramble), blowup, password
[FAIL] create a patch image, none8
[FAIL] create a patch image, none8
[FAIL] patch an image (descramble), none8
[FAIL] patch an image (descramble), none8

Some bugs i found right away:

    data.extend(chunk_Type, hiByte, loByte)
^ this needs a list, thus the code does not execute at all

 elif chunkType == 4 and versionStored == 1:
...
received_params = pickle.loads(bytes(chunkData))
received_param = json.loads(bytearray(chunkData).decode("utf-8"))
^ this change cripples json decoding (as received_params is used) and all files version 2 and up should not decode. V1 uses pickles, V2 uses json

Did the new code run on your side with an image with scramble and descramble? It does not on my side with the test setup and some spontanous test images.

I will however take changes you introduced (like sorting of functions in the code, some renames) into account, and also reading into PEP8 (I am not a python "native"). Also I hope I find the bugs you corrected (if you could point me to these that would be great!) But I will not just merge the pull request, as reformatting introduces too much diffs i cannot compare because of time available :-(

**Comment by dzhalaevd** [comment]
> Started to looking into, sorry, I had no time before -- ok, I have to go through the code more in deep, it takes a lot of time since also format is changed (spaces vs tab etc) -- so diff with "eyes"
> 
> First test run almost resulted in all Fail, sorry :-O
> 
...
> 
> Some bugs i found right away:
> 
> ```
> data.extend(chunk_Type, hiByte, loByte)
> ```
> 
> ^ this needs a list, thus the code does not execute at all
> 
> elif chunkType == 4 and versionStored == 1: ... received_params = pickle.loads(bytes(chunkData)) received_param = json.loads(bytearray(chunkData).decode("utf-8")) ^ this change cripples json decoding (as received_params is used) and all files version 2 and up should not decode. V1 uses pickles, V2 uses json
> 
> Did the new code run on your side with an image with scramble and descramble? It does not on my side with the test setup and some spontanous test images.
> 
> I will however take changes you introduced (like sorting of functions in the code, some renames) into account, and also reading into PEP8 (I am not a python "native"). Also I hope I find the bugs you corrected (if you could point me to these that would be great!) But I will not just merge the pull request, as reformatting introduces too much diffs i cannot compare because of time available :-(

I am confused by these lines

Firstly:
```python
scrambler = received_params[SCRAMBLERPARAMETERSDATAFIELD_SCRAMBLER]
```

In this line we have a warning ```Unrelated local variables```  for var: ```received_params```. And we need to use ```global```, but I tried and I got an error and this is also a bad practice. Therefore, I think it would be better to write a function to which we will pass these variables into parameters.

Secondly:
```python
myRestoredBytes, marginLeft, marginTop = deserialize(savedim, totalBlocks + 3)
```
In this line we have a warning ```Redeclared names without usages``` for var: ```marginLeft, marginTop```. I think we can just remove them from this line, but since I didn't run the tests, I'm not 100% sure and that this will solve your problem.

Thirdly:
```python 
if isDisguiseEnabled:
    im.paste(thumb, (0, 0), mask=None)
```
var ```thumb``` has the same problem as in the first case ()


and, as I wrote above, there are problems ```(nesting, parentheses)``` with the if condition, variable naming, very large functions. All these problems are not serious, but complicate the readability of the code.
It seems that's all

**Pull request closed without merging**
